### ISSUE TITLE
As an unregistered user, I want to register myself using personal credentials in order to be able to log in.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#1]
# Acceptance Criteria

- [ ] Only with valid credentials a new user can register itself (both username and password have to be non-empty) 
- [ ] Error displayed if password and confirm password don’t match. (front-end implementation only)
- [ ] Another user with the same name cannot be registered --> error message will indicate that this username is already taken  
- [ ] A username with ä, ö etc. Is not valid and an error message will show up that specifies that the username must be written differently 
- [ ] After the registration, the user is automatically logged in and directed to the personal profile 

# Development Tasks
## Backend: 
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#32
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#144
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#29
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#30

## Frontend:
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#1
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#2
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#80
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#3

# Notes

- Only Latin letters in username 
- No restriction for password  
- The user needs to confirm his password
- Password and Confirm password need to be the same
- No users with same name, same password is ok 
- Letters like ö, ü etc need to be written as oe etc. by the user (otherwise an error message will show up) 
- After the registration, the user is directed to the personal profile to further define it
