### ISSUE TITLE
As a host, I want to be able to invite other users to the group in order to start planning.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#10]
# Acceptance Criteria 

- [x] The host sees all names of online users  
- [x] There is a button to invite users 
- [x] Only a host can invite users to a group 
- [x] The host sees who is has accepted the invitation (guests then) 
- [x] There is a button to either continue or cancel the group 

# Development Tasks

## Backend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#131
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#132
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#133
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#134
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#135

## Frontend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#71
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#72
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#73
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#74
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#75
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#76
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#77
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#78

# Notes 
- This happens in the GROUP CREATION PAGE 
- The host sees a list with all available users and can invite them 
- One user can be in only one group at a time 
- A group has minimum 2 group members: The host and another guest 
- After the invitations are send, the host transitions to the GROUP FORMING PAGE–HOST VIEW
