### ISSUE TITLE
As a host, I have to choose a voting type, in order to support decision making later on.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#11]
# Notes 
- This happens in the GROUP CREATION PAGE 
- 2 voting types/logics: majority vote (default for the beginning) and point distribution 
- Host has to decide while creating the group 

# Acceptance Criteria 

- [x] The host gets information in text form about the voting systems 
- [x] The host can choose maximum one option.  
- [x] The decision is stored and displayed (later) in the GROUP FORMING PAGES

## Backend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#172
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#173

## Frontend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#99
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#100
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#101

**Comment by wlany** [comment]
disclaimer: as of our submission a host cannot choose another option from Majority, as it's the only voting logic that is implemented
