### ISSUE TITLE
As a host, I want to choose whether to accept or reject join requests for the group, in order to have control over who is joining my group.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#13]
# Notes 
- This happens in the GROUP FORMING PAGE - HOST VIEW 
- The host can either accept or deny join requests 

# Acceptance Criteria

- [x] The host sees the name of the user who wants to join the group 
- [x] The host can accept or deny the request  

## Backend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#171
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#168
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#169
- [x] #218

## Frontend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#96
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#97
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#98
