### ISSUE TITLE
As a host, while being on the GROUP FORMING PAGE - HOST VIEW, I can click drop whole group / continue button, in order to drop the whole group or continue with the meal planning process

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#14]
# Notes 
- The host is responsible to continue the process. 
- If the host clicks continue, the process continues

# Acceptance Criteria 

- [x] Only the host can continue on the process, the guests have mark to themselves ready and wait
- [x] The host can continue the process by clicking the continue button only if there is at least one ready guest in the group.  
- [x] The host cannot delete the group once at least one member is ready
- [x] The host can only continue if all his guests are ready

# Development Tasks
## Backend:

- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#77
- [x] #114

## Frontend:

- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#39
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#40
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#41
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#42
