### ISSUE TITLE
As a guest, I see a GROUP FORMING PAGE - GUEST VIEW, and I can decide to drop out of the group or continue, in order to leave a group with people I do not like or show the host that I am ready to continue to the meal planning process.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#15]
# Notes 
- The GROUP FORMING PAGE gives an overview 
- Guests can decide to drop out or to continue the process (=be ready button) 
- It includes: name of the group, host, all members, voting system 

# Acceptance Criteria 

- [x] By clicking on the ready button the user is shown a lobby screen to wait for the host to continue the process 

# Development Tasks
## Backend:

- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#67
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#69

## Frontend:

- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#34
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#35
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#36
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#37 
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#144
