### ISSUE TITLE
As a guest and host, I want to type in all ingredients I have in my fridge/storage room, in order to let others know what I can contribute for the meal. 

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#16]
# Notes 
- Every guest and the host have to add minimum one ingredient, she/he wants to contribute 
- Each item is listed on its own 
- The user can finally submit her/his contributions 

# Development Tasks 
## Backend: 
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#104
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#105
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#197
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#210

## Frontend: 
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#57
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#58
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#59
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#60
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#61
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#62
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#63
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#133

# Acceptance Criteria 

- [x] A user has to add one ingredient minimum to be able to click the "continue" button 
- [x] All contributions are listed separately 
- [x] There is a button to submit the final contributions

**Comment by chiaralentsch** [comment]
Add task "Display the overall allergies of the group **if any**" for frontend
