### ISSUE TITLE
As a guest and host, I want to see an overview of all ingredients, my friends want to contribute, in order to rate them according to my preferences.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#17]
# Acceptance Criteria

- [x] A guest has to rate all ingredients depending on the decision logic 
- [x] Only if a user has rated all ingredients, the submit button can be clicked  

# Development Tasks
## Backend: 
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#64
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#65

## Frontend:
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#28
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#27
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#26
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#25
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#125
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#126

# Notes 
- All users have to independently rate all listed ingredients 
- The rating is done either on majority vote or point distribution

**Comment by chiaralentsch** [comment]
modify task #24 from "Display an overview of all ingredients for the suggested recipe, along with the names of the guests who have contributed each ingredient." to "Display an overview of all ingredients that have been typed in by the guests so that they can rate them"
