### ISSUE TITLE
As a guest I then see the final ingredients, in order to have a better overview.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#19]
# Acceptance Criteria 

- [x] Ingredients that were voted out are not displayed
- [x] All members (host and guests) can see the final ingredients
- [x] For the final recipe these final ingredients are going to be used
- [x] The ingredients voted out are not used for the final recipe

# Development Tasks
## Backend: 
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#60

## Frontend:
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#19
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#127

**Comment by chiaralentsch** [comment]
Add "Create a final ingredients page with the ingredients that have been selected after the voting"
