### ISSUE TITLE
As a user, I want to have a "Go Solo" option, in case I don't want to eat with friends tonight, but still want to use the benefits of the recipe's suggestions feature. 

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#23]
# Notes
- If the “Go Solo” is chosen, the user is transitioned to the recipe page directly
- the suggestion is based on the information in the personal profile

# Acceptance Criteria

- [x] There is a button at the LANDING PAGE, which offer the "Go Solo" 
- [x] By clicking this button, the user is directed to a recipe page
- [x] The recipe is chosen based on the users' profile

## Backend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#268
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#269

## Frontend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#145

**Comment by akkuebler** [comment]
we shortened this user story by deleting the option to type in ingredients. The recipe is only based on the information given in the profile

**Comment by wlany** [comment]
deleted task #146 because it was unecessary
