### ISSUE TITLE
As a registered user, I want to log out, in order to leave the app.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#3]
# Acceptance Criteria 

- [ ] After the logout the user is guided to the Login page
- [ ] After the logout the status of the user is changed to offline 
- [ ] Logout button is always accessible 

# Development Tasks
## Backend:

- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#47

## Frontend:

- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#10
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#11
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#12

# Notes 

- Only users which are logged in, can log out 
- All the time a logout button is accessible 
- If a user logs out and therefore leaves the planning group, the other users which formed a group with him, get a notification. 
- After the logout, the user is guided to the starting page where he/she can login again
