### ISSUE TITLE
As a registered user, I want to change my username and password, in order to secure my data.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#4]
# Acceptance Criteria 

- [ ] A user can change the password using the same restrictions as defined above in userstory 1.) 
- [ ] A user can change his/her password and has to login again afterwards 
- [ ] There exist no users with the same name 

# Notes 
- Changing the username is only possible if there is no other user with this name already. If so, a warning message occurs, specifying that the new username is already taken 
- For changing the password, the actual password has to be typed in as well before. This password needs to be correct and the same as the confirmed password. 
- After that, the user has to login again with his new password  

## backend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#176
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#177

## frontend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#94
