### ISSUE TITLE
As a registered user, I want to add more information to my profile in order to support me while planning the meal with my friends.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#5]
# Acceptance Criteria 

- [ ] Only the user itself can add the additional information 
- [ ] Information in the user profile is shown in separate lists 
- [ ] Every other user can see them by visiting the user profile (clicking on the user name on the LANDING PAGE) 

# Development Tasks
## Backend:

- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#106
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#87
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#88

## Frontend:

- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#45
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#46
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#47
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#48
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#49
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#50
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#51
- [ ] sopra-fs23-group-03/sopra-fs23-group-03-client#112

# Notes 
- After registering, the user is redirected to the profile page 
- The profile page is also accessible from the LANDING PAGE 
- Additional information are: Allergies, favourite cuisine and special diet (vegan, vegetarian, etc.) ; those information are displayed in the user profile 
- They can be edited only via an edit button 
- The editing can be saved via a save button and can be cancelled via a cancel button.
