### ISSUE TITLE
 As a user I want to see all other users and the other groups on the LANDING PAGE, in order to decide whether I want to be the host or not.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#6]
# Notes
- There is a list of all users which are registered in the app 
- Each existing group with its group name is listed and all guests are displayed

# Development Tasks
## Backend:

- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#101
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#102
- [x] #159

## Frontend:

- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#52
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#53
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#54
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#55
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#56
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#9
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#79

# Acceptance Criteria

- [x] All registered users are listed with the online users being displayed in the beginning of the list and the offline users being displayed after the online ones
- [x] A user can click on the username to get to the respective user profile 
- [x] All active planning groups are listed
