### ISSUE TITLE
As a future host, I want to click on a button, in order to start the group planning process.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#7]
# Acceptance Criteria

- [ ] Any user can click on a button to start the group planning process 
- [ ] This user is then assigned as the host 
- [ ] The user is then redirected to the GROUP CREATION PAGE

# Development Tasks

## Backend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#123
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#124
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#125
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#126
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#127

## Frontend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#68
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#69
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#70

# Notes

- The future host is then directed to the GROUP CREATION PAGE 
- If a user starts the group planning process, he is automatically assigned as the host 
- There is always exactly one host (= user who originally created the group) 
- One user can be the host of exactly one group at a time. 
- The host has to assign a name to the group of friends, which is used to display the group at the LANDING PAGE
