### ISSUE TITLE
As a user, I want to see all already existing groups on the LANDING PAGE, in order to request one of them to join.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#8]
# Notes 
- Display of all existing groups with name, the host and all the guests
- Display a join button next to the groups that are available 

# Acceptance Criteria 

- [x] A user can send a join request via a button 
- [x] If this button is still clickable, the user can send a request 
- [x] If the group has already started planning the meal, there is no option of joining the group 

## Backend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#167
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#170

## Frontend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#95
