### ISSUE TITLE
As a user, I can get an invitation through a notification to join an existing group, in order to either accept or decline it.

### ISSUE THREAD

**Issue by akkuebler** [sopra-fs23-group-03/sopra-fs23-group-03-server#9]
# Acceptance Criteria 

- [x] A user can get an invitation 
- [x] A user can see the guests, the host and the voting system of the group that she/he got an invitation from 
- [x] The user can either accept or decline the invitation 
- [x] If the user joins, she/he transitions to a GROUP FORMING PAGE – GUEST VIEW  
- [x] If the user declines, she/he goes back to the LANDING PAGE 

# Development Tasks

## Backend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#115
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#117
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#118
- [x] sopra-fs23-group-03/sopra-fs23-group-03-server#119
- [x] #157

## Frontend
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#64
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#65
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#66
- [x] sopra-fs23-group-03/sopra-fs23-group-03-client#67

# Notes 
- After a user clicks on the notification, he/she is redirected to  GROUP FORMING PAGE – GROUP OVERVIEW 
- In the GROUP FORMING PAGE – GROUP OVERVIEW one can see all the guests and the host and the voting system 
- The user is given the option to either join or decline
